version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: es01
    hostname: es01
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../es_data/es01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - ../../cert/ca/ca.crt:/usr/share/elasticsearch/config/cert/ca.crt
      - ../../cert/es01/es01.crt:/usr/share/elasticsearch/config/cert/es01.crt
      - ../../cert/es01/es01.key:/usr/share/elasticsearch/config/cert/es01.key
    ports:
      - 19200:19200
      - 19300:19300

