version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: es02
    hostname: es02
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../es_data/es02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
    ports:
      - 29200:9200
      - 29300:9300

